[package]
name = "neopolitan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
logos = "0.12.1"
nom = "7.1.3"
serde = { version = "1.0.154", features = ["derive"] }
serde_json = "1.0.94"


[lib]
doctest = false
