[package]
name = "neopolitan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0.0"
minijinja = "0.30.5"
nom = "7.1.3"


[lib]
doctest = false

