#!/bin/bash

tput clear
for i in $( seq 1 $(tput lines))
do
  echo ""
done

cargo test -q -- --nocapture

if [[ $? -eq 0 ]]
then 
  tput setaf 28
else
  tput setaf 124
fi

export BAR=$(($(tput cols) * 1))
for i in $( seq 1 $BAR); do printf '%s' '█'; done
tput sgr0
